force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usando para armazenar as habilidades dos heróis ou vilões.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção  entre os objetos Contato e Habilidade.</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <description>Campo de relacionamento entre Habilidade e Contato.</description>
    <inlineHelpText>Campo de relacionamento entre Habilidade e Contato.</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>Habilidades_do_Contato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de relacionamento entra Habilidade de Contato com Habilidade.</description>
    <inlineHelpText>Campo de relacionamento entra Habilidade de Contato com Habilidade.</inlineHelpText>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactCreatTask.cls
global class ContactCreatTask {
	
    @InvocableMethod(label = 'Criar Tarefa para Contato')
    public Static void ContactCreateTask(List<CreateTaskRequest> requests){
        System.debug('>>> requests ::' + requests);
        
        List<Id> lstCotatctIds = new List<Id>();
        for(CreateTaskRequest request : requests)
            lstCotatctIds.add(request.contactId);
        
        System.debug('>>> lstCotatctIds ::' + lstCotatctIds);
        
        //CRIA E POPULA UMA LISTA DAS HABILIDADES DO CONTATO
        List<HabilidadeContato__c> lstHabContatos = [select Id, Contato__c, Habilidade__r.Name from HabilidadeContato__c where Contato__c in : lstCotatctIds];
          
        //CRIA UM MAP
        Map<Id, List<String>> mapContatoHabilidades = new Map<Id, List<String>>(); 
        
        //PERCORRE AS HABILIDADES 
        for( HabilidadeContato__c habilidadeContato : lstHabContatos ){    
            
            //VERIFICA SE EXISTE ESSE ID DO CONTATO NO MAP
            if( mapContatoHabilidades.containsKey( habilidadeContato.Contato__c ) ){
                //ADD HABILIDADE PARA O ID EXISTENTE
                mapContatoHabilidades.get( habilidadeContato.Contato__c ).add( habilidadeContato.Habilidade__r.Name );
            }else{
                //ADD UMA LISTA DE STRING NO ID DO MAP
                mapContatoHabilidades.put( habilidadeContato.Contato__c, new List<String>{habilidadeContato.Habilidade__r.Name});               
            }
            System.debug('>>> mapContatoHabilidades DENTRO ::' + mapContatoHabilidades);            
        }        
        System.debug('>>> mapContatoHabilidades FORA ::' + mapContatoHabilidades);
        
        CreatTasks(requests, mapContatoHabilidades); 	 	 	 
    }
       
    //"CreatTasks" ASSUME A VISIBILIDADE DO MÉTODO CHAMADO POR ELE
    public static void CreatTasks(List<CreateTaskRequest> requests, Map<Id, List<String>> mapContatoHabilidades){
        
        System.debug('>>> requests ::' + requests);
        List<task> tasksToInsert = new List<Task>();
        
         for(CreateTaskRequest request : requests){
            Task tarefa = new Task(); 	 
                tarefa.Subject 		= request.subject;
                tarefa.WhoId 		= request.contactId;
                tarefa.OwnerId 		= request.ownerId;
                tarefa.Status 		= 'Open';
             	tarefa.Description 	= 'Por favor avalie este heroi. Suas habilidades são: '+ String.valueOf(mapContatoHabilidades.get(request.contactId));
             tasksToInsert.add(tarefa);
             
             if( !tasksToInsert.isEmpty() )
            insert tasksToInsert;
        }
    }   

    //CLASSE PARA RECEBER OS DADOS DO PORCESS BUILDER USANDO A VISIBILIDADE "global"
    global class CreateTaskRequest{
         //"@InvocableVariable" ASSINATURA PARA VARIAVEL SER USADA NO PROCESS BUILDER
         //(required = true) FORÇA O PREENCHIMENTO NO PROCESS BUILDER
         @InvocableVariable(required = true)
         global String contactId;
         @InvocableVariable(required = true)
         global String ownerId;
         @InvocableVariable
         global String subject;
    }
}