force-app/main/default/objects/BatalhasContato__c/BatalhasContato__c.object-meta.xml
<CustomObject>
    <description>Batalhas em que o Contato participou.</description>
    <label>Batalhas do Contato</label>
    <nameField>
        <displayFormat>BTLCTT{000000}</displayFormat>
        <label>Batalha do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batalhas do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BatalhasContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de relacionamento entre Batalhas do Contato e Contato</description>
    <inlineHelpText>Campo de relacionamento entre Batalhas do Contato e Contato</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Batalhas do Contato</relationshipLabel>
    <relationshipName>BatalhasContatoContato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NivelHerio__c.field-meta.xml
<CustomField>
    <fullName>NivelHerio__c</fullName>
    <description>Nível de senioridade do herói.</description>
    <inlineHelpText>Nível de senioridade do herói.</inlineHelpText>
    <label>Nível do Heriói</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aspira</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Pleno</fullName>
            </value>
            <value>
                <fullName>Sênior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NomeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeGuerra__c</fullName>
    <description>Nome  do herói ou nome do vilão.</description>
    <externalId>true</externalId>
    <inlineHelpText>Nome  do herói ou nome do vilão.</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Heroi.recordType-meta.xml
<RecordType>
    <fullName>Heroi</fullName>
    <active>true</active>
    <label>Herói</label>
</RecordType>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usando para armazenar as habilidades dos heróis ou vilões.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção  entre os objetos Contato e Habilidade.</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <description>Campo de relacionamento entre Habilidade e Contato.</description>
    <inlineHelpText>Campo de relacionamento entre Habilidade e Contato.</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>Habilidades_do_Contato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de relacionamento entra Habilidade de Contato com Habilidade.</description>
    <inlineHelpText>Campo de relacionamento entra Habilidade de Contato com Habilidade.</inlineHelpText>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Level_Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Level_Habilidade__c</fullName>
    <description>Level da Habilidade do Herói</description>
    <inlineHelpText>Insira o valor do nível da Habilidade para esse Herói</inlineHelpText>
    <label>Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GetAvailablesIS.cls
/*Lista todos os heróis que ñ estão alocados em batalhas e 
 * ter opção de buscar todos, por habilidade e por nível do heroi 
 */
//@RestResource -> ASSINATURA PARA SER ACESSIVEL VIA API
//urlMapping ->CAMINHO QUE VAMOS CHAMAR NOSSO ENDPOIT PARA DEVOLVER A INFORMAÇÃO 
@RestResource(urlMapping='/marvel/vailablesheroes/*') // MAPAPEI O SERVIÇO PARA AS APIs
global class GetAvailablesIS {
        
    //SERVIÇO DO TIPO GET
    @HttpGet // INFORMA QUAL O MÉTODO SERA USADO,  
    global static AvailableHeroes doGet(){
        
       
        // lista para receber o resultado da query
        List<HabilidadeContato__c> lstHabContatos = new List<HabilidadeContato__c>();
        
        //mapa de string, contato 
        Map<String,Hero> mapHerois = new Map<String,Hero>();
        
        //PARAMETROS RECEBIDOS DA API
        String habilidadeParam = RestContext.request.params.get('habilidade');
        String nivelParam = RestContext.request.params.get('niveil');
        
        //query
        String dynamicQuery = 'SELECT Id, Contato__r.NomeGuerra__c, Contato__r.Name,Contato__r.NivelHerio__c, Habilidade__r.Name, Level_Habilidade__c '+
            			'FROM HabilidadeContato__c ' +
            			'WHERE Contato__r.RecordType.DeveloperName = \'Heroi\' '+
            			'AND Contato__c NOT IN (select Contato__c from BatalhasContato__c)';
        
        if(!String.isBlank(habilidadeParam)){
            //cria uma lista para receber um ou + parametros 
            List<String> listHabilidadesParam = habilidadeParam.split(',');
            //add + uma condição na query
            dynamicQuery += ' and Habilidade__r.Name IN : listHabilidadesParam';
        }
        if(!String.isBlank(nivelParam)){
             List<String> listNiveisParam = nivelParam.split(',');
            dynamicQuery += ' and Contato__r.NivelHerio__c IN : listNiveisParam';
        }
        
        system.debug('dynamicQuery: '+ dynamicQuery);
        
        //obtem o retorno da query
        lstHabContatos = DataBase.query(dynamicQuery);
       
        for(HabilidadeContato__c habilidadeContato : lstHabContatos){

            Skill habilidade = new Skill(habilidadeContato.Habilidade__r.Name,String.valueOf(habilidadeContato.Level_Habilidade__c));
        	Hero heroi;
             //VERIFICA SE EXISTE ESSE ID DO CONTATO NO MAP
            if( mapHerois.containsKey( habilidadeContato.Contato__r.Name ) ){
                //RECUPERAR O VALOR DO MAPA PASSANDO A CHAVE
                heroi = mapHerois.get( habilidadeContato.Contato__r.Name );
                //ADD HABILIDADE PARA O CONTATO RECUPERADO
                heroi.habilidades.add(habilidade);                
            }else{
                //INSTANCIA DO NOVO HEROI
                heroi =  new Hero();
                //ATRIBIU OS VALORES PARA OS ATRIBUTOS
                heroi.nome = habilidadeContato.Contato__r.Name;
                heroi.nivel = habilidadeContato.Contato__r.NivelHerio__c;
                heroi.habilidades = new List<Skill>{habilidade};             
            }
             // ADD OS NOVOS VALORES AO MAPA
             mapHerois.put( habilidadeContato.Contato__r.Name, heroi); 
        }
                
         system.debug('Mapa Herois: '+ mapHerois);
        
        //return availableHeroes;
        return new AvailableHeroes (mapHerois.values());
    }
    
    //ESTRUTURA PARA Ñ EXPOR IFORMAÇÕES DESNECESSARIAS NA API
    global class AvailableHeroes{
        public List<Hero> herois;
        public Integer total;
        public AvailableHeroes(List<Hero> herois){
            this.herois = herois;
            this.total = herois.size();
        }
    } 
    global class Hero{
        String nome;
        String nivel;
        public List<Skill> habilidades;
    }
    global class Skill{
        String nome;
        String nivel;        
        Skill(String nome, String nivel){
            this.nome = nome;
            this.nivel = nivel != null ? nivel : 'Não avaliado';
        }
    }
}