force-app/main/default/objects/Contact/fields/NivelHerio__c.field-meta.xml
<CustomField>
    <fullName>NivelHerio__c</fullName>
    <description>Nível de senioridade do herói.</description>
    <inlineHelpText>Nível de senioridade do herói.</inlineHelpText>
    <label>Nível do Heriói</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aspira</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Pleno</fullName>
            </value>
            <value>
                <fullName>Sênior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status_Candidato__c.field-meta.xml
<CustomField>
    <fullName>Status_Candidato__c</fullName>
    <description>Informa se o contato esta apto ou não para o treinamento.</description>
    <inlineHelpText>Informa se o contato esta apto ou não para o treinamento.</inlineHelpText>
    <label>Status Candidato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Análise</fullName>
                <default>true</default>
                <label>Em Análise</label>
            </value>
            <value>
                <fullName>Reprovado na Análise</fullName>
            </value>
            <value>
                <fullName>Aguardando aprovação para o Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado na Análise do Gestor</fullName>
            </value>
            <value>
                <fullName>Em Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado no Treinamento</fullName>
                <label>Reprovando no Treinamento</label>
            </value>
            <value>
                <fullName>Aprovado no Treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado Direto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção  entre os objetos Contato e Habilidade.</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Level_Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Level_Habilidade__c</fullName>
    <description>Level da Habilidade do Herói</description>
    <inlineHelpText>Insira o valor do nível da Habilidade para esse Herói</inlineHelpText>
    <label>Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IdentificarnNivelHeroiFlow.cls
global class IdentificarnNivelHeroiFlow {
    
    @InvocableMethod(label = 'Identificar Nível do Herói')
    public Static List<Contact> identificaNivelHeroi(List<contactRequest> requests){

        System.debug('requests :' + requests);
        List<Contact> contatos = new List<Contact>();
        
        //PERCORRENDO CADA CONTATO
        for(contactRequest request : requests){
            Decimal media = 0;
            Decimal somaLevel = 0;
            
            System.debug('request.habilidadesContato :'+ request.habilidadesContato);
            //PERCORRENDO CADA HABILIDADE DO CANTADO
            for(HabilidadeContato__c habilidadeContato : request.habilidadesContato){
               	somaLevel += habilidadeContato.Level_Habilidade__c; 
                System.debug('2º for - somaLevel :' + somaLevel);
                
            }
            
            media = somaLevel/request.habilidadesContato.size();
            System.debug('media :' + media);
          
             String nivel = '';
            if(media >= 80){
            	nivel = 'Sênior'; 	   
            }else if(media >= 50){
                nivel = 'Pleno';
            }else{
                nivel = 'Junior';
            }
            
            
            System.debug('nivel :' + nivel);
           // contatos.add(new Contact(Id = request.contactId, NivelHerio__c = nivel, ));
            System.debug('Habilidades Contato :'+ request);
            request.contact.NivelHerio__c = nivel;
           // request.contact.Status_Candidato__c = 'Aprovado no Treinamento';
            contatos.add(request.contact);
        }
        
        update contatos;
        return contatos;
    }

     global class contactRequest{
         @InvocableVariable(required = true)
         global Contact contact;
         @InvocableVariable(required = true)
         global List<HabilidadeContato__c> habilidadesContato;
    }
}