force-app/main/default/objects/Contact/fields/NomeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeGuerra__c</fullName>
    <description>Nome  do herói ou nome do vilão.</description>
    <externalId>true</externalId>
    <inlineHelpText>Nome  do herói ou nome do vilão.</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status_Candidato__c.field-meta.xml
<CustomField>
    <fullName>Status_Candidato__c</fullName>
    <description>Informa se o contato esta apto ou não para o treinamento.</description>
    <inlineHelpText>Informa se o contato esta apto ou não para o treinamento.</inlineHelpText>
    <label>Status Candidato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Análise</fullName>
                <default>true</default>
                <label>Em Análise</label>
            </value>
            <value>
                <fullName>Reprovado na Análise</fullName>
            </value>
            <value>
                <fullName>Aguardando aprovação para o Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado na Análise do Gestor</fullName>
            </value>
            <value>
                <fullName>Em Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado no Treinamento</fullName>
                <label>Reprovando no Treinamento</label>
            </value>
            <value>
                <fullName>Aprovado no Treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado Direto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usando para armazenar as habilidades dos heróis ou vilões.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção  entre os objetos Contato e Habilidade.</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <description>Campo de relacionamento entre Habilidade e Contato.</description>
    <inlineHelpText>Campo de relacionamento entre Habilidade e Contato.</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>Habilidades_do_Contato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de relacionamento entra Habilidade de Contato com Habilidade.</description>
    <inlineHelpText>Campo de relacionamento entra Habilidade de Contato com Habilidade.</inlineHelpText>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Level_Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Level_Habilidade__c</fullName>
    <description>Level da Habilidade do Herói</description>
    <inlineHelpText>Insira o valor do nível da Habilidade para esse Herói</inlineHelpText>
    <label>Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/NomeHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NomeHabilidade__c</fullName>
    <description>Nome da Habilidade do Contato.</description>
    <formula>Habilidade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Nome da Habilidade do Contato.</inlineHelpText>
    <label>Nome da Habilidade</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>Colocação do Nível do Herói.</description>
    <inlineHelpText>Selecionar as maiores Habilidades do Herói.</inlineHelpText>
    <label>Ranking</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AtualizaRankingHabilidadeTriggerTest.cls
@isTest
public class AtualizaRankingHabilidadeTriggerTest {
    
    @testSetup
    public static void setup(){
        // objs utilizados: Contato - Hablidade do Contato - Habilidade
       
       	Contact capitaoAmerica = new Contact(FirstName= 'Steve', LastName= 'Rogers', NomeGuerra__c= 'Capitão America', Status_Candidato__c= 'Aprovado Direto');
        Contact viuvaNegra = new Contact(FirstName= 'Natasha', LastName= 'Romanoff', NomeGuerra__c= 'Viúva Negra', Status_Candidato__c= 'Aprovado Direto');

        List<Contact> herois = new List<Contact>{capitaoAmerica, viuvaNegra};
        insert herois;
        
        Habilidade__c arteMarcial = new Habilidade__c(Name='Arte Marcial');
        Habilidade__c atirador = new Habilidade__c(Name='Atirador');
        Habilidade__c superForca = new Habilidade__c(Name='Super Forçe');
        
        List<Habilidade__c> habilidades = new List<Habilidade__c>{superForca, atirador, arteMarcial};
        insert habilidades;
        
        HabilidadeContato__c habilidadeContato1 = new HabilidadeContato__c();
        habilidadeContato1.Contato__c = capitaoAmerica.Id;
        habilidadeContato1.Habilidade__c = superForca.id;
        habilidadeContato1.Level_Habilidade__c = 90;
        
        HabilidadeContato__c habilidadeContato2 = new HabilidadeContato__c();
        habilidadeContato2.Contato__c = capitaoAmerica.Id;
        habilidadeContato2.Habilidade__c = atirador.id;
        habilidadeContato2.Level_Habilidade__c = 80;
        
        HabilidadeContato__c habilidadeContato3 = new HabilidadeContato__c();
        habilidadeContato3.Contato__c = capitaoAmerica.Id;
        habilidadeContato3.Habilidade__c = arteMarcial.id;
        habilidadeContato3.Level_Habilidade__c = 50;
        
        
        HabilidadeContato__c habilidadeContato4 = new HabilidadeContato__c();
        habilidadeContato4.Contato__c = viuvaNegra.Id;
        habilidadeContato4.Habilidade__c = arteMarcial.id;
        habilidadeContato4.Level_Habilidade__c = 70;
        
        HabilidadeContato__c habilidadeContato5 = new HabilidadeContato__c();
        habilidadeContato5.Contato__c = viuvaNegra.Id;
        habilidadeContato5.Habilidade__c = atirador.id;
        
        HabilidadeContato__c habilidadeContato6 = new HabilidadeContato__c();
        habilidadeContato6.Contato__c = viuvaNegra.Id;
        habilidadeContato6.Habilidade__c = superForca.id; 
             
       
        List<HabilidadeContato__c> habilidadesContato = new List<HabilidadeContato__c>{habilidadeContato1, habilidadeContato2, habilidadeContato3, habilidadeContato4, habilidadeContato5, habilidadeContato6};
        System.debug('habilidadesContato: '+ habilidadesContato);
        insert habilidadesContato;
        
        List<HabilidadeContato__c> habilidadesContatoDelete = new List<HabilidadeContato__c>{habilidadeContato6};
        delete habilidadesContatoDelete;      
        
        habilidadeContato4.Level_Habilidade__c = 83;
        habilidadeContato5.Level_Habilidade__c = 78;
        List<HabilidadeContato__c> habilidadesContatoUpdate = new List<HabilidadeContato__c>{habilidadeContato4,habilidadeContato5};        
        update habilidadesContatoUpdate;
    }
    
    @isTest
    public static void validaNovoRankingAfterInsert(){
        List<HabilidadeContato__c> habilidadesContato = [SELECT id, NomeHabilidade__c, Ranking__c   
                                                        FROM HabilidadeContato__c
                                                         WHERE Contato__r.NomeGuerra__c = 'Capitão America'
                                                        and Ranking__c != null];
        
        for(HabilidadeContato__c habilidadeContato : habilidadesContato){
            
            switch on habilidadeContato.NomeHabilidade__c {
                
                when 'Super Força'{
                    System.assertEquals(1, habilidadeContato.Ranking__c);
                }
                when 'Atirador'{
                    System.assertEquals(2, habilidadeContato.Ranking__c);
                }
                when 'Arte Marcial'{
                    System.assertEquals(3, habilidadeContato.Ranking__c);
                }when else{
                    
                }
            }
        }
       
    }
    
}