force-app/main/default/objects/Contact/fields/NomeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeGuerra__c</fullName>
    <description>Nome  do herói ou nome do vilão.</description>
    <externalId>true</externalId>
    <inlineHelpText>Nome  do herói ou nome do vilão.</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usando para armazenar as habilidades dos heróis ou vilões.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção  entre os objetos Contato e Habilidade.</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <description>Campo de relacionamento entre Habilidade e Contato.</description>
    <inlineHelpText>Campo de relacionamento entre Habilidade e Contato.</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>Habilidades_do_Contato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de relacionamento entra Habilidade de Contato com Habilidade.</description>
    <inlineHelpText>Campo de relacionamento entra Habilidade de Contato com Habilidade.</inlineHelpText>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Level_Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Level_Habilidade__c</fullName>
    <description>Level da Habilidade do Herói</description>
    <inlineHelpText>Insira o valor do nível da Habilidade para esse Herói</inlineHelpText>
    <label>Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/NomeHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NomeHabilidade__c</fullName>
    <description>Nome da Habilidade do Contato.</description>
    <formula>Habilidade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Nome da Habilidade do Contato.</inlineHelpText>
    <label>Nome da Habilidade</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EstudoSOQL.cls
public class EstudoSOQL {
	
    public static List<Contact> getAllContatcts(){
        List<Contact> contatos = [SELECT id, Name FROM contact];
        return contatos;
    }
    
    public static Contact getContactById(Id contactId){
        Contact contato = [SELECT id, Name, NomeGuerra__c FROM contact where id = :contactId];
       // return contato;        
        //List<Contact> contatos = [SELECT id, Name, NomeGuerra__c FROM contact where id = :contactId];
        
        if(contato != null){
            return contato;
        }else{
        	return null;    
        }
    }
    public static Map<String, Decimal> getAvgContact(){
        //USADO PARA TER MAIS FACILIDADE COM RESULTADOS AGRUPADOS 
        AggregateResult[] results = [SELECT Contato__r.NomeGuerra__c NomeGuerra, AVG(Level_Habilidade__c) MediaLevel
                                    FROM HabilidadeContato__c 
                                    GROUP BY Contato__r.NomeGuerra__c
                                    HAVING AVG(Level_Habilidade__c) > 0
                                    ORDER BY AVG(Level_Habilidade__c) DESC];                                        
       
        Map<String, Decimal> mapa = new Map<String, Decimal>();
        for(AggregateResult agResult : results){
            //
            String nomeGuerra = (String) agResult.get('NomeGuerra');
            Decimal madiaLevel = (Decimal) agResult.get('MediaLevel'); 
            
            mapa.put(nomeGuerra,madiaLevel);
        }
        
       return mapa;
    }
    
    public static List<HabilidadeContato__c> getHabilidaddePorContatoOrHabilidade(String nomeGuerra, String nomeHabilidade){
        String query = 'select id, Habilidade__r.Name, Level_Habilidade__c from HabilidadeContato__c where ';
        
        if(!String.isEmpty(nomeGuerra)){
            query += 'Contato__r.NomeGuerra__c = : nomeGuerra';
        }else{
            query += 'Habilidade__r.Name = :nomeHabilidade';
		}
         System.debug('>>> query ::' + query);
        List<HabilidadeContato__c> habilidadeContato = dataBase.query(query);
  
        System.debug('>>> return ::' + habilidadeContato);
        return habilidadeContato;
    }
}

/* MACETE => MAPA RECEBENDO UMA CONSULTA DIRETA
Map<Id, Contact> mapContatosRevisarRanking = new Map<Id, Contact>([SELECT id,
                                                                               (SELECT id, Name, Level_Habilidade__c 
                                                                                FROM Habilidades_do_Contato__r 
                                                                                WHERE Level_Habilidade__c != null 
                                                                                ORDER BY Level_Habilidade__c DESC, NomeHabilidade__c)
                                                                               FROM Contact 
                                                                               WHERE Id in : idsContato])

 */